
.PHONY: test-deps web-assets rb-driver py-driver
test-deps: $(BUILD_DIR)/rethinkdb $(BUILD_DIR)/rethinkdb-unittest web-assets rb-driver py-driver

# Stub targets for legacy dependencies not yet ported to Python 3.
# web-assets:   generated by scripts/compile-web-assets.py (Python 2→3 migration needed)
# rb-driver:    Ruby driver build (not needed for unit/RQL tests)
# py-driver:    Python driver build (not needed for unit/RQL tests)
.PHONY: web-assets rb-driver py-driver
web-assets rb-driver py-driver:
	@true

.PHONY: test
test: test-deps
	$P RUN-TESTS $(TEST)
	MAKEFLAGS= $/test/run $(RUN_TEST_ARGS) -b $(BUILD_DIR) $(TEST)

.PHONY: full-test
full-test: TEST = all
full-test: test
